version: "3"

services:
  web:
    build: web
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ${PROJECT_PATH}:/var/www/html:rw,delegated
      - /var/www/html/node_modules
    tty: true

  mysql:
    build: mysql
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    tty: true

  maildev:
    image: djfarrelly/maildev
    env_file: .env
    depends_on:
      - web
    ports:
      - "1088:80"
    tty: true

volumes:
  mysql: {}
